Use NOAA-GSL/EMC_post RRFS_dev branch to apply the lastest version of…
NOAA-GSL/ufs-srweather-app pull request #7
Opened 2021-01-14 07:47 UTC by hu5970

2021-01-14 17:15 UTC, christinaholtNOAA requested changes
Ming, please make sure that you are providing short title description, and leaving the details in the discussion box when submitting a PR.

2021-01-14 17:15 UTC, christinaholtNOAA commented on Externals.cfg
> +#hash = 9b9c55c
Please use a particular hash for the code that you would like to use. Using the top of a branch for workflows running in real time is hard to reconstruct for future use if we need to rebuild.

2021-01-14 20:21 UTC, hu5970 commented
@christinaholtNOAA Changed to use hash instead of top of the branch. Thanks,

2021-01-22 00:18 UTC, hu5970 commented
@christinaholtNOAA Christina, it there further change needed for merge this? Thanks, Ming

2021-01-22 19:11 UTC, christinaholtNOAA approved these changes

2021-01-22 19:11 UTC, merged